version: '3.0'
 
services:
   db:
    image: mysql:5.7
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    ports:
       - "42333:3306"
    volumes: 
       - dbdata:/var/lib/mysql
       - ./MySQL_Init_Script:/docker-entrypoint-initb.d
    restart: always

   accountownerapp:
     depends_on: 
       - db
     image: dockerizing/accountowner:runtime
     build: 
        context: .
     ports:
       - "8080:5000"

volumes:
    dbdata: