version: '3.1'
 
services:
   db:
    image: mysql:5.7
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes: 
       - dbdata:/var/lib/mysql
       - ./MySQL_Init_Script:/docker-entrypoint-initb.d
    restart: always

   accountownerapp:
     depends_on: 
       - db
     image: my-registry:50000/dockerizing/accountowner:build-2
   integration:
     depends_on: 
       - accountownerapp
     image: my-registry:50000/dockerizing/accountowner:test
     build: 
        context: .
        dockerfile: Dockerfile.Integration
     ports:
       - "8080:5000"

volumes:
    dbdata: